/* Canonical editable schema. Blank means unknown, never zero or approved. */
window.HaloManufactureData = {
  storageKey: 'halo-manufacture-workspace-v1',
  revision: 'rigid-chassis-installed-readability-v2',
  dimensions: [
    ['wrist-diameter', 'Wrist inner diameter (legacy / general envelope)', 'mm / size range — re-review against two-size strategy'],
    ['size-sm', 'S/M chassis target envelope', 'TARGET ONLY — curvature / internal envelope / revision'],
    ['size-ml', 'M/L chassis target envelope', 'TARGET ONLY — curvature / internal envelope / revision'],
    ['size-coverage', 'Two-size fit evidence', 'Wrist samples / overlap / comfort / tool-free adjustment'],
    ['underside-travel', 'Underside adjustment travel', 'TARGET 15–20 mm; final travel requires fit prototype'],
    ['wrist-curvature', 'Rigid upper wrist curvature', 'Approx. front 2/3; arc / radii / section / CAD revision'],
    ['clasp-architecture', 'Clasp / adjustment candidate', 'Candidate mechanism / closure feedback / accidental release'],
    ['current-indexing', 'Current-stone center alignment', 'Mechanism / sequence / Months 01–12 / retention evidence'],
    ['module-envelope', 'Complete removable module envelope', 'Stone + carrier + NFC / antenna / isolation, mm'],
    ['pinch-points', 'Skin pinch / sharp-edge clearance', 'Clasp, moving underside, module edges / inspection revision'],
    ['pvd-allowance', 'PVD thickness / fit allowance', 'Supplier process range / masking / tolerance stack'],
    ['isolation-volume', 'NFC isolation / antenna volume', 'Space for spacer / ferrite / antenna alternatives, mm'],
    ['assembly-access', 'Assembly / replacement access', 'Sequence / fixture / setting / service access'],
    ['exposure', 'Water / sweat exposure provisions', 'Materials / drainage / corrosion and seal tests; no rating assumed'],
    ['wall', 'Bracelet wall thickness', 'mm'], ['width', 'Bracelet width', 'mm'],
    ['height', 'Bracelet height', 'mm'], ['hinge', 'Hinge clearance', 'mm'],
    ['clasp', 'Clasp clearance', 'mm'], ['stone-diameter', 'Stone diameter', 'mm'],
    ['pitch', 'Stone / socket pitch', 'mm, center to center'], ['socket-diameter', 'Socket diameter', 'mm'],
    ['socket-depth', 'Socket depth', 'mm'], ['tabs', 'Locking tab geometry', 'Geometry / revision'],
    ['angle', 'Installation rotation angle', 'Degrees'], ['carrier', 'Stone carrier thickness', 'mm'],
    ['undercut', 'Undercut', 'mm / process'], ['ferrite', 'Ferrite allowance', 'mm / grade'],
    ['antenna', 'NFC antenna cavity', 'Diameter × depth, mm'], ['seat', 'Gemstone seat', 'mm / setting'],
    ['seal', 'Gasket / seal, if used', 'Material / section or N/A'], ['drainage', 'Drainage', 'Path / opening or N/A'],
    ['skin', 'Skin-side clearance', 'mm'], ['removal', 'Removal access', 'Method / clearance'],
    ['tool', 'Service tool possibility', 'Tool / access or N/A'], ['tolerances', 'Manufacturing tolerance stack', 'Datum / fit / ± mm'],
    ['minimum-wall', 'Minimum wall thickness', 'mm / DFM constraint'], ['engraving', 'Engraving area', 'Location / dimensions'],
    ['blank-profile', 'Flush filler profile / diameter', 'mm / edge height / radial brushing'],
    ['blank-retention', 'Filler retention & removal', 'Interface / tool / spare storage'],
    ['stone-crown', 'Stone cut & crown height', 'Cabochon vs faceted dome / mm'],
    ['bezel-rim', 'Bezel rim / stone protection', 'mm / retention / exposed crown'],
    ['pack-envelope', 'Master box outer envelope', 'Final TBD — reference 280 × 160 × 45 mm conflicts', 'packaging'],
    ['pack-board', 'Board, wrap & lining stack', 'Board gauge / texture / finish', 'packaging'],
    ['pack-bracelet-bay', 'Bracelet bay / package location', 'Separate protected position; Month 01 immediately accessible', 'packaging'],
    ['pack-first-box', 'Month 01 location / box envelope', 'One of exactly 12 branded boxes; accessible first', 'packaging'],
    ['pack-month-boxes', 'Milestone boxes / calibrated envelope', 'Final TBD — reference 60 × 60 × 45 mm conflicts', 'packaging'],
    ['pack-drawer', 'Collection tray / drawer & travel', '12-box arrangement / internal fit / access, mm', 'packaging'],
    ['pack-fit', 'Drawer fit / divider pitch', 'Clearance / tolerance stack, mm', 'packaging'],
    ['pack-insert', 'Stone nest / removable insert', 'Cavity / material / safe extraction', 'packaging'],
    ['pack-ribbon', 'Ribbon pull / anchor detail', 'Material / pull length / retention target', 'packaging'],
    ['pack-cards', 'Ritual card / print specification', 'Size / stock / print / finish', 'packaging'],
    ['pack-protection', 'Transit / closure protection', 'Crown clearance / movement / carton allowance', 'packaging'],
    ['pack-finish-match', 'Shared Light / Dark dieline verification', 'Same inserts, cards, graphics, type and stone order; color only', 'packaging']
  ],
  protocol: [
    ['revision', 'CAD / sample revision', 'TBD — link every result to the tested geometry'],
    ['reader', 'Phone / reader / app / OS', 'TBD — model, case, foreground vs background mode'],
    ['distance', 'Defined tap distance & fixture', 'TBD — mm, phone landmark, dwell and orientation'],
    ['loose-target', 'Loose / removed readability criterion', 'TBD — successes / attempts at defined distances'],
    ['installed-target', 'Legacy installed criterion — superseded', 'Historical only; may have tested suppression. Do not use to approve readability.', 'legacy'],
    ['installed-readability-target', 'NEW final installed readability criterion', 'TBD — successful reads / attempts; on/off wrist, geometry and identity'],
    ['partial-readability-target', 'Partially integrated readability criterion', 'TBD — assembly stage / fixture / successful reads / attempts'],
    ['rf-attempts', 'RF repeatability sample plan', 'TBD — attempts, modules, phones, orientations and repetitions'],
    ['mechanical-target', 'Module retention / pull-off criterion', 'TBD — load, direction, fixture, conditioning and acceptance'],
    ['clasp-cycles', 'Clasp cycle plan & acceptance', 'TBD — cycles / force / accidental contact / failures'],
    ['adjustment-cycles', 'Underside adjustment cycle plan', 'TBD — cycles / travel / drift / wear / acceptance'],
    ['replacement-cycles', 'Stone replacement cycle plan', 'TBD — insert/remove cycles / tool use / retention re-test'],
    ['flex-torsion', 'Wrist flex / torsion plan', 'TBD — fixture / load / repetitions / both chassis sizes'],
    ['sweat-corrosion', 'Sweat / corrosion exposure plan', 'TBD — method / duration / conditions / inspection criteria'],
    ['pvd-abrasion', 'Dark PVD abrasion plan', 'TBD — process sample / thickness / rub method / acceptance'],
    ['scratch-resistance', 'Scratch resistance plan', 'TBD — method / surface / reference / acceptable damage'],
    ['drop-test', 'Bracelet / module drop plan', 'TBD — height / orientation / surface / repeats / damage criteria'],
    ['pinch-inspection', 'Pinch / edge inspection plan', 'TBD — moving states / gauges / skin clearance / reject criteria'],
    ['test-evidence', 'Test owner / evidence / status', 'TBD — date / operator / raw logs / photos / criteria revision']
  ],
  rf: [
    ['prototype', 'Prototype ID / CAD revision'],
    ['requirement', 'Requirement basis', ['Current installed-readability requirement', 'Legacy — re-review required']],
    ['evidence', 'Evidence status', ['REQUIRES PROTOTYPE', 'DESIGN INTENT', 'WORKING ASSUMPTION', 'SUPPLIER-CONFIRMED', 'PHYSICALLY VALIDATED']],
    ['chassis', 'Chassis size / geometry'], ['finish', 'Finish / PVD revision'],
    ['chip', 'NFC chip / inlay'], ['antenna', 'Antenna envelope (mm)'],
    ['ferrite', 'Ferrite type / thickness'], ['isolation', 'Isolation / spacer / antenna location'],
    ['carrier', 'Carrier / socket materials'], ['loose', 'Loose module read'],
    ['partial', 'Partially integrated read'], ['installed', 'Final installed read'],
    ['wrist', 'Installed on wrist'], ['removed', 'Removed read / post-cycle'],
    ['phone', 'Phone model / OS / case'], ['reader', 'Reader mode / app'],
    ['distance', 'Read distance (mm) / dwell'], ['orientation', 'Orientation / phone landmark'],
    ['repeatability', 'Successes / attempts / identity check'], ['conditioning', 'Mechanical / exposure conditioning'],
    ['proof', 'Raw evidence / date / operator'], ['notes', 'Notes / criteria revision'],
    ['result', 'Pass / fail for stated requirement', ['Not tested', 'In progress', 'Pass', 'Fail', 'Inconclusive']]
  ],
  quotes: [
    ['supplier', 'Supplier'], ['country', 'Country'], ['component', 'Program component'], ['process', 'Process'],
    ['program', 'Shared HALO program / CAD revision'], ['size', 'S/M + M/L scope / size mix'],
    ['finishScope', 'Finish scope', ['Unconfirmed', 'Shared Light + Dark', 'Light only', 'Dark incremental premium']],
    ['moq', 'MOQ / combined finish terms'], ['tooling', 'Shared tooling (one-time)'], ['sample', 'Sample cost'], ['unit25', 'Unit @25'],
    ['unit100', 'Unit @100'], ['unit500', 'Unit @500'], ['unit1000', 'Unit @1000'],
    ['lead', 'Lead time'], ['material', 'Material / stone identity'], ['tolerance', 'Tolerance / PVD allowance'], ['finish', 'Finish process / premium'],
    ['inclusions', 'Included processes / quote basis'], ['yield', 'Yield / scrap basis'],
    ['evidence', 'Evidence status', ['WORKING ASSUMPTION', 'DESIGN INTENT', 'REQUIRES PROTOTYPE', 'SUPPLIER-CONFIRMED', 'PHYSICALLY VALIDATED']],
    ['proof', 'Written quote / sample evidence'],
    ['contact', 'Contact'], ['status', 'Status', ['Not contacted', 'Contacted', 'Awaiting quote', 'Comparing', 'Sampling', 'Qualified', 'Rejected']],
    ['sampleOrdered', 'Sample ordered', ['No', 'Yes', 'Received']], ['notes', 'Notes']
  ],
  decisions: [
    ['topic', 'Decision / open question'], ['intent', 'Current direction / alternatives'],
    ['status', 'Evidence status', ['DESIGN INTENT', 'WORKING ASSUMPTION', 'REQUIRES PROTOTYPE', 'SUPPLIER-CONFIRMED', 'PHYSICALLY VALIDATED']],
    ['owner', 'Owner / target date'], ['revision', 'CAD / requirement revision'],
    ['evidence', 'Supporting evidence / limitations'], ['next', 'Next proof / gate']
  ]
};
